USE `TPI-Manager`;

INSERT INTO `TPI-Manager`.collaborators (email,acronym,lastName,firstName,isResponsableTPI)
VALUES 
('patrick.altieri@cpnv.ch','PAI','ALTIERI','Patrick',0),
('Frederique.ANDOLFATTO@cpnv.ch','FAO','ANDOLFATTO','Frederique',0),
('pascal.benzonana@cpnv.ch','PBA','BENZONANA','Pascal',0),
('claude-chantal.blanc@cpnv.ch','CBC','BLANC','Claude Chantal',0),
('eric.bouthiaux@cpnv.ch','EBX','BOUTHIAUX','Eric',0),
('blaise.brocard@cpnv.ch','BBD','BROCARD','Blaise',0),
('Yann.CHARRERE@cpnv.ch','YCE','CHARRERE','Yann',0),
('jean-philippe.chavey@cpnv.ch','JCY','CHAVEY','Jean-Philippe',0),
('gabriel.cimenti@cpnv.ch','GCI','CIMENTI','Gabriel',0),
('christine.codourey@cpnv.ch','CCY','CODOUREY','Christine',0),
('Massimiliano.CRICCO@cpnv.ch','MCO','CRICCO','Massimiliano',0),
('marc.dafflon@cpnv.ch','MDN','DAFFLON','Marc',0),
('thierry.de-heller@cpnv.ch','TDR','DE HELLER','Thierry',0),
('Ana.DE-LAMEGO-RESENDE@cpnv.ch','ARE','DE-LAMEGO-RESENDE','Ana',0),
('stephane.delaporte@cpnv.ch','SDE','DELAPORTE','Stéphane',0),
('Valerie.DILLET@cpnv.ch','VDT','DILLET','Valerie',0),
('sylvain.fasola@cpnv.ch','SFA','FASOLA','Sylvain',0),
('raphael.favre@cpnv.ch','RFA','FAVRE','Raphaël',0),
('Olivia.FERRIERO@cpnv.ch','OFO','FERRIERO','Olivia',0),
('Nicolas.GLASSEY@cpnv.ch','NGY','GLASSEY','Nicolas',0),
('Yoachim.GRABER@cpnv.ch','YGR','GRABER','Yoachim',0),
('Cindy.HARDEGGER@cpnv.ch','CHA','HARDEGGER','Cindy',0),
('pascal.hurni@cpnv.ch','PHI','HURNI','Pascal',0),
('Julien.ITHURBIDE@cpnv.ch','JIE','ITHURBIDE','Julien',0),
('laurent.jaggi@cpnv.ch','LJI','JAGGI','Laurent',0),
('charles-henri.kohli@cpnv.ch','CKI','KOHLI','Charles-Henri',0),
('Yawo.KONOUTSE@cpnv.ch','YKE','KONOUTSE','Yawo',0),
('Agnes.LAYAZ@cpnv.ch','ALZ','LAYAZ','Agnes',0),
('sophie-helene.martin@cpnv.ch','SMM','MARTIN','Sophie-Hélène',0),
('Joelle.MATTER@cpnv.ch','JMR','MATTER','Joëlle',0),
('Mathieu.MEYLAN@cpnv.ch','MMN','MEYLAN','Mathieu',0),
('judith.mondada@cpnv.ch','JMA','MONDADA','Judith',0),
('andre.mottier@cpnv.ch','AMR','MOTTIER','André',0),
('Alessio.PARATA@cpnv.ch','APA','PARATA','Alessio',0),
('claude.rochat@cpnv.ch','CRT','ROCHAT','Claude',0),
('monika.ryser@cpnv.ch','MRY','RYSER','Monika',0),
('yann.saison@cpnv.ch','YSN','SAISON','Yann',0),
('Julien.SAVARY@cpnv.ch','JSY','SAVARY','Julien',0),
('yvan.thiery@cpnv.ch','YTY','THIERY','Yvan',0),
('jean-yves.tinembart@cpnv.ch','JTT','TINEMBART','Jean-Yves',0),
('francis.varela@cpnv.ch','FVA','VARELA','Francis',0),
('Loic.VIRET@cpnv.ch','LVT','VIRET','Loic',0),
('didier.wulliamoz@cpnv.ch','DWZ','WULLIAMOZ','Didier',0),
('Michael.WYSSA@cpnv.ch','MWA','WYSSA','Michael',0)
;