-- MySQL Script generated by MySQL Workbench
-- Wed Feb  8 12:11:33 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema TPI-Manager
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TPI-Manager
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `TPI-Manager`;

CREATE SCHEMA IF NOT EXISTS `TPI-Manager` DEFAULT CHARACTER SET utf8 ;
USE `TPI-Manager` ;

-- -----------------------------------------------------
-- Table `TPI-Manager`.`Classes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TPI-Manager`.`Classes` ;

CREATE TABLE IF NOT EXISTS `TPI-Manager`.`Classes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TPI-Manager`.`Candidates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TPI-Manager`.`Candidates` ;

CREATE TABLE IF NOT EXISTS `TPI-Manager`.`Candidates` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `lastName` VARCHAR(100) NOT NULL,
  `firstName` VARCHAR(100) NOT NULL,
  `Classes_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Classes_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_Class` (`Classes_id` ASC) VISIBLE,
  CONSTRAINT `fk_Candidates_Classes1`
    FOREIGN KEY (`Classes_id`)
    REFERENCES `TPI-Manager`.`Classes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `TPI-Manager`.`Collaborators`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TPI-Manager`.`Collaborators` ;

CREATE TABLE IF NOT EXISTS `TPI-Manager`.`Collaborators` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `acronym` VARCHAR(3) NOT NULL,
  `lastName` VARCHAR(100) NOT NULL,
  `firstName` VARCHAR(100) NOT NULL,
  `isResponsableTPI` TINYINT NOT NULL DEFAULT 0,
  `password` VARCHAR(45) NOT NULL DEFAULT '1234',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `TPI-Manager`.`TPI`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TPI-Manager`.`TPI` ;

CREATE TABLE IF NOT EXISTS `TPI-Manager`.`TPI` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) NOT NULL,
  `year` DATE NOT NULL,
  `remarks` VARCHAR(2000) NULL,
  `duration` INT NULL,
  `CDC` VARCHAR(200) NULL,
  `Candidates_id` INT NOT NULL,
  `Collaborators_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Candidates_id`, `Collaborators_id`),
  UNIQUE INDEX `title_UNIQUE` (`title` ASC) VISIBLE,
  INDEX `fk_Candidate` (`Candidates_id` ASC) VISIBLE,
  INDEX `fk_Collaborator` (`Collaborators_id` ASC) VISIBLE,
  CONSTRAINT `fk_TPI_Candidates1`
    FOREIGN KEY (`Candidates_id`)
    REFERENCES `TPI-Manager`.`Candidates` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TPI_Collaborators1`
    FOREIGN KEY (`Collaborators_id`)
    REFERENCES `TPI-Manager`.`Collaborators` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TPI-Manager`.`Technologies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TPI-Manager`.`Technologies` ;

CREATE TABLE IF NOT EXISTS `TPI-Manager`.`Technologies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `siteLink` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TPI-Manager`.`Experts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TPI-Manager`.`Experts` ;

CREATE TABLE IF NOT EXISTS `TPI-Manager`.`Experts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `lastName` VARCHAR(100) NOT NULL,
  `firstName` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TPI-Manager`.`TPI_has_Experts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TPI-Manager`.`TPI_has_Experts` ;

CREATE TABLE IF NOT EXISTS `TPI-Manager`.`TPI_has_Experts` (
  `TPI_id` INT NOT NULL,
  `Experts_id` INT NOT NULL,
  PRIMARY KEY (`TPI_id`, `Experts_id`),
  INDEX `fk_Expert` (`Experts_id` ASC) VISIBLE,
  INDEX `fk_TPI` (`TPI_id` ASC) VISIBLE,
  CONSTRAINT `fk_TPI_has_Experts_TPI`
    FOREIGN KEY (`TPI_id`)
    REFERENCES `TPI-Manager`.`TPI` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TPI_has_Experts_Experts1`
    FOREIGN KEY (`Experts_id`)
    REFERENCES `TPI-Manager`.`Experts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TPI-Manager`.`TPI_uses_Technologies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TPI-Manager`.`TPI_uses_Technologies` ;

CREATE TABLE IF NOT EXISTS `TPI-Manager`.`TPI_uses_Technologies` (
  `TPI_id` INT NOT NULL,
  `Technologies_id` INT NOT NULL,
  PRIMARY KEY (`TPI_id`, `Technologies_id`),
  INDEX `fk_Technologie` (`Technologies_id` ASC) VISIBLE,
  INDEX `fk_TPI` (`TPI_id` ASC) VISIBLE,
  CONSTRAINT `fk_TPI_has_Technologies_TPI1`
    FOREIGN KEY (`TPI_id`)
    REFERENCES `TPI-Manager`.`TPI` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TPI_has_Technologies_Technologies1`
    FOREIGN KEY (`Technologies_id`)
    REFERENCES `TPI-Manager`.`Technologies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



-- ====================================================================================================
-- INSERT DATA
-- ====================================================================================================

-- -----------------------------------------------------
-- Table `TPI-Manager`.`collaborators`
-- -----------------------------------------------------
INSERT INTO `TPI-Manager`.collaborators (email,acronym,lastName,firstName,isResponsableTPI)
VALUES 
('patrick.altieri@cpnv.ch','PAI','ALTIERI','Patrick',0),
('Frederique.ANDOLFATTO@cpnv.ch','FAO','ANDOLFATTO','Frederique',0),
('pascal.benzonana@cpnv.ch','PBA','BENZONANA','Pascal',0),
('claude-chantal.blanc@cpnv.ch','CBC','BLANC','Claude Chantal',0),
('eric.bouthiaux@cpnv.ch','EBX','BOUTHIAUX','Eric',0),
('blaise.brocard@cpnv.ch','BBD','BROCARD','Blaise',0),
('Yann.CHARRERE@cpnv.ch','YCE','CHARRERE','Yann',0),
('jean-philippe.chavey@cpnv.ch','JCY','CHAVEY','Jean-Philippe',0),
('gabriel.cimenti@cpnv.ch','GCI','CIMENTI','Gabriel',0),
('christine.codourey@cpnv.ch','CCY','CODOUREY','Christine',0),
('Massimiliano.CRICCO@cpnv.ch','MCO','CRICCO','Massimiliano',0),
('marc.dafflon@cpnv.ch','MDN','DAFFLON','Marc',0),
('thierry.de-heller@cpnv.ch','TDR','DE HELLER','Thierry',0),
('Ana.DE-LAMEGO-RESENDE@cpnv.ch','ARE','DE-LAMEGO-RESENDE','Ana',0),
('stephane.delaporte@cpnv.ch','SDE','DELAPORTE','Stéphane',0),
('Valerie.DILLET@cpnv.ch','VDT','DILLET','Valerie',0),
('sylvain.fasola@cpnv.ch','SFA','FASOLA','Sylvain',0),
('raphael.favre@cpnv.ch','RFA','FAVRE','Raphaël',0),
('Olivia.FERRIERO@cpnv.ch','OFO','FERRIERO','Olivia',0),
('Nicolas.GLASSEY@cpnv.ch','NGY','GLASSEY','Nicolas',0),
('Yoachim.GRABER@cpnv.ch','YGR','GRABER','Yoachim',0),
('Cindy.HARDEGGER@cpnv.ch','CHA','HARDEGGER','Cindy',1),
('pascal.hurni@cpnv.ch','PHI','HURNI','Pascal',0),
('Julien.ITHURBIDE@cpnv.ch','JIE','ITHURBIDE','Julien',0),
('laurent.jaggi@cpnv.ch','LJI','JAGGI','Laurent',0),
('charles-henri.kohli@cpnv.ch','CKI','KOHLI','Charles-Henri',0),
('Yawo.KONOUTSE@cpnv.ch','YKE','KONOUTSE','Yawo',0),
('Agnes.LAYAZ@cpnv.ch','ALZ','LAYAZ','Agnes',0),
('sophie-helene.martin@cpnv.ch','SMM','MARTIN','Sophie-Hélène',0),
('Joelle.MATTER@cpnv.ch','JMR','MATTER','Joëlle',0),
('Mathieu.MEYLAN@cpnv.ch','MMN','MEYLAN','Mathieu',0),
('judith.mondada@cpnv.ch','JMA','MONDADA','Judith',0),
('andre.mottier@cpnv.ch','AMR','MOTTIER','André',0),
('Alessio.PARATA@cpnv.ch','APA','PARATA','Alessio',0),
('claude.rochat@cpnv.ch','CRT','ROCHAT','Claude',0),
('monika.ryser@cpnv.ch','MRY','RYSER','Monika',0),
('yann.saison@cpnv.ch','YSN','SAISON','Yann',0),
('Julien.SAVARY@cpnv.ch','JSY','SAVARY','Julien',0),
('yvan.thiery@cpnv.ch','YTY','THIERY','Yvan',0),
('jean-yves.tinembart@cpnv.ch','JTT','TINEMBART','Jean-Yves',0),
('francis.varela@cpnv.ch','FVA','VARELA','Francis',0),
('Loic.VIRET@cpnv.ch','LVT','VIRET','Loic',0),
('didier.wulliamoz@cpnv.ch','DWZ','WULLIAMOZ','Didier',0),
('Michael.WYSSA@cpnv.ch','MWA','WYSSA','Michael',0)
;

-- -----------------------------------------------------
-- Table `TPI-Manager`.`classes`
-- -----------------------------------------------------
INSERT INTO `TPI-Manager`.classes (name)
VALUES 
('SI-C1a'),
('SI-C1b'),
('SI-C2a'),
('SI-C2b'),
('SI-C3a'),
('SI-C3b'),
('SI-C4a'),
('SI-C4b'),
('SI-C4r'),
('SI-CA1a'),
('SI-CA2a'),
('SI-MI1a'),
('SI-MI1b'),
('SI-MI2a'),
('SI-MI2b'),
('SI-MI3a'),
('SI-MI3b'),
('SI-MI4a'),
('SI-MI4b'),
('SM-CA1a'),
('SM-CA2a'),
('SP-CA1a'),
('SP-CA2a'),
('YA-CA1a'),
('YA-CA2a'),
('YAD-CA2a'),
('YAD-CA4a'),
('YS-CA2a'),
('YS-CA2b')
;

-- -----------------------------------------------------
-- Table `TPI-Manager`.`candidates`
-- -----------------------------------------------------
INSERT INTO `TPI-Manager`.candidates (email,lastName,firstName,Classes_id)
VALUES 
('Marc-Antoine.ABOUD@cpnv.ch','ABOUD','Marc-Antoine',15),
('Yasin-Salih.AKYUZ@cpnv.ch','AKYUZ','Yasin-Salih',10),
('Kathleen.ANAND@cpnv.ch','ANAND','Kathleen',28),
('Zacharie.ANDRE@cpnv.ch','ANDRE','Zacharie',28),
('Elod.ARIFI@cpnv.ch','ARIFI','Elod',2),
('Erfan.ASHKAN@cpnv.ch','ASHKAN','Erfan',20),
('Kenan.AUGSBURGER@cpnv.ch','AUGSBURGER','Kenan',18),
('Yanira-Aracely.AVEIGA-RODRIGUEZ@cpnv.ch','AVEIGA-RODRIGUEZ','Yanira-Aracely',28),
('Xavier.AZEVEDO-JESUS@cpnv.ch','AZEVEDO-JESUS','Xavier',1),
('Pedro.BARCHA-NETO@cpnv.ch','BARCHA-NETO','Pedro',20),
('Corentin-Mikael.BARDET@cpnv.ch','BARDET','Corentin-Mikael',11),
('Tristan.BARRAS@cpnv.ch','BARRAS','Tristan',11),
('Alex.BARREIRA-VIDEIRA@cpnv.ch','BARREIRA-VIDEIRA','Alex',3),
('Ryan.BERSIER@cpnv.ch','BERSIER','Ryan',1),
('Morgane.BEURET@cpnv.ch','BEURET','Morgane',23),
('Yoann.BONZON@cpnv.ch','BONZON','Yoann',7),
('Maxime.BORGEAUD@cpnv.ch','BORGEAUD','Maxime',10),
('Jean-Amedee.BOSCH@cpnv.ch','BOSCH','Jean-Amedee',7),
('Timothee-Tristan.BOSSY@cpnv.ch','BOSSY','Timothee-Tristan',28),
('Arthur.BOTTEMANNE@cpnv.ch','BOTTEMANNE','Arthur',5),
('Gaetan.BRAILLARD@cpnv.ch','BRAILLARD','Gaetan',29),
('Theo.BROCARD@cpnv.ch','BROCARD','Theo',4),
('Ken.CACCIABUE@cpnv.ch','CACCIABUE','Ken',20),
('Ryan.CARDAMONE@cpnv.ch','CARDAMONE','Ryan',2),
('Joao-Alexandre.CARVALHO-SANTOS@cpnv.ch','CARVALHO-SANTOS','Joao-Alexandre',3),
('Simone.CATHERINE@cpnv.ch','CATHERINE','Simone',29),
('Rojhat.CEYLAN@cpnv.ch','CEYLAN','Rojhat',20),
('Nathan.CHAUVEAU@cpnv.ch','CHAUVEAU','Nathan',6),
('Daniel.CHEVALLEY@cpnv.ch','CHEVALLEY','Daniel',4),
('Quentin.CLORY@cpnv.ch','CLORY','Quentin',22),
('Ian.CLOT@cpnv.ch','CLOT','Ian',10),
('Nathanael.COLLAUD@cpnv.ch','COLLAUD','Nathanael',18),
('Benjamin.CONSTANTIN@cpnv.ch','CONSTANTIN','Benjamin',29),
('Luke.CORNAZ@cpnv.ch','CORNAZ','Luke',7),
('Maikol.CORREIA-DA-SILVA@cpnv.ch','CORREIA-DA-SILVA','Maikol',10),
('Athos.CRUCHET@cpnv.ch','CRUCHET','Athos',2),
('Simon.CUANY@cpnv.ch','CUANY','Simon',7),
('Tiago.DA-COSTA-LOURENCO@cpnv.ch','DA-COSTA-LOURENCO','Tiago',2),
('Matteo.DA-CUNHA@cpnv.ch','DA-CUNHA','Matteo',4),
('Diogo.DA-SILVA-FERNANDES@cpnv.ch','DA-SILVA-FERNANDES','Diogo',17),
('David.DA-SILVA-SOARES@cpnv.ch','DA-SILVA-SOARES','David',5),
('Amin.DE-ABREU-JDIDI@cpnv.ch','DE-ABREU-JDIDI','Amin',4),
('Kevin.DE-ALMEIDA-GOMES@cpnv.ch','DE-ALMEIDA-GOMES','Kevin',8),
('Andre.DE-CARVALHO-VARELA-BATISTA@cpnv.ch','DE-CARVALHO-VARELA-BATISTA','Andre',11),
('Daniel.DE-PINHO-LOPES-FERREIRA@cpnv.ch','DE-PINHO-LOPES-FERREIRA','Daniel',14),
('Nathalie.DELEVAUX@cpnv.ch','DELEVAUX','Nathalie',20),
('Edona.DELIU@cpnv.ch','DELIU','Edona',28),
('Nicolas.DENARIE@cpnv.ch','DENARIE','Nicolas',22),
('Elodie.DEPIERRAZ@cpnv.ch','DEPIERRAZ','Elodie',6),
('Nora.DIZEKO@cpnv.ch','DIZEKO','Nora',20),
('Mathieu.DORMOND@cpnv.ch','DORMOND','Mathieu',21),
('Jessica.DOS-SANTOS-ANDRADE-DOMINGUES@cpnv.ch','DOS-SANTOS-ANDRADE-DOMINGUES','Jessica',29),
('Leo.DUTOIT@cpnv.ch','DUTOIT','Leo',25),
('Hadi-Alistair.EL-MOUSSAOUI@cpnv.ch','EL-MOUSSAOUI','Hadi-Alistair',21),
('Nolan.EVARD@cpnv.ch','EVARD','Nolan',19),
('Yann.FANHA-DIAS@cpnv.ch','FANHA-DIAS','Yann',7),
('Benjamin.FAVRE@cpnv.ch','FAVRE','Benjamin',21),
('Julien.FAVRE2@cpnv.ch','FAVRE2','Julien',25),
('Carlos-Miguel.FERREIRA-DA-SILVA@cpnv.ch','FERREIRA-DA-SILVA','Carlos-Miguel',2),
('Tibo.FERREIRA-DE-CARVALHO@cpnv.ch','FERREIRA-DE-CARVALHO','Tibo',5),
('Blinar.FETIU@cpnv.ch','FETIU','Blinar',1),
('Christophe.FONSECA-DIOGO@cpnv.ch','FONSECA-DIOGO','Christophe',1),
('Benjamin.FONTANA@cpnv.ch','FONTANA','Benjamin',7),
('Caitlin.FORSYTH@cpnv.ch','FORSYTH','Caitlin',28),
('Bastien.FUCARINO@cpnv.ch','FUCARINO','Bastien',28),
('Celine.GAILLARD@cpnv.ch','GAILLARD','Celine',20),
('Jeremie.GAILLARD@cpnv.ch','GAILLARD','Jeremie',28),
('Luca.GATTO@cpnv.ch','GATTO','Luca',8),
('Mateus.GEBREMICAEL@cpnv.ch','GEBREMICAEL','Mateus',20),
('Naomie.GERBER@cpnv.ch','GERBER','Naomie',28),
('Paul-Loup.GERMAIN@cpnv.ch','GERMAIN','Paul-Loup',6),
('Theo.GHIELMINI@cpnv.ch','GHIELMINI','Theo',11),
('Loic.GIGANDET@cpnv.ch','GIGANDET','Loic',1),
('Martin.GLAUSER@cpnv.ch','GLAUSER','Martin',13),
('Gabriel.GLOOR@cpnv.ch','GLOOR','Gabriel',17),
('Vanessa.GOMES-DOS-SANTOS@cpnv.ch','GOMES-DOS-SANTOS','Vanessa',28),
('Joao-Pedro.GONCALVES-AIRES@cpnv.ch','GONCALVES-AIRES','Joao-Pedro',12),
('Sylvie.GONZALEZ-FIDALGO@cpnv.ch','GONZALEZ-FIDALGO','Sylvie',28),
('Andreas.GRANADA@cpnv.ch','GRANADA','Andreas',8),
('Adam.GRUBER@cpnv.ch','GRUBER','Adam',9),
('Quentin.GUEISSAZ@cpnv.ch','GUEISSAZ','Quentin',5),
('Mathias.GUIGNARD@cpnv.ch','GUIGNARD','Mathias',7),
('Robin.GUMY@cpnv.ch','GUMY','Robin',11),
('Maxime.GUMY@cpnv.ch','GUMY','Maxime',20),
('Shanshe.GUNDISHVILI@cpnv.ch','GUNDISHVILI','Shanshe',8),
('Christophe.HAGER@cpnv.ch','HAGER','Christophe',20),
('Simao.HENRIQUES-SILVA@cpnv.ch','HENRIQUES-SILVA','Simao',3),
('Romain.HUMBERT-DROZ-LAURENT@cpnv.ch','HUMBERT-DROZ-LAURENT','Romain',6),
('Danis.IBRAHIMOVIC@cpnv.ch','IBRAHIMOVIC','Danis',1),
('Luca.ISELI@cpnv.ch','ISELI','Luca',20),
('John.JACCARD@cpnv.ch','JACCARD','John',13),
('Liam.JACCARD@cpnv.ch','JACCARD','Liam',2),
('Sacha.JACCARD@cpnv.ch','JACCARD','Sacha',3),
('Leo.JAQUIER@cpnv.ch','JAQUIER','Leo',4),
('Eliott.JAQUIER@cpnv.ch','JAQUIER','Eliott',8),
('Cyprien.JAQUIER@cpnv.ch','JAQUIER','Cyprien',7),
('Christopher-Philippe.JAUREGUI@cpnv.ch','JAUREGUI','Christopher-Philippe',2),
('Coralie.JENNY@cpnv.ch','JENNY','Coralie',20),
('Baptiste.JOLY@cpnv.ch','JOLY','Baptiste',22),
('Mikael.JUILLET@cpnv.ch','JUILLET','Mikael',8),
('Kushtrim.JUSUFI@cpnv.ch','JUSUFI','Kushtrim',2),
('Amine-Mohamed.KADDOURI@cpnv.ch','KADDOURI','Amine-Mohamed',2),
('Maria-da-Conceicao.KLEIN@cpnv.ch','KLEIN','Maria-da-Conceicao',29),
('Timothe.KOBEL@cpnv.ch','KOBEL','Timothe',4),
('Thierry.KOETSCHET@cpnv.ch','KOETSCHET','Thierry',11),
('Christophe.KUNZLI@cpnv.ch','KUNZLI','Christophe',11),
('Geraldine.LACROIX@cpnv.ch','LACROIX','Geraldine',28),
('Jimmy-Gia-Bao.LAM@cpnv.ch','LAM','Jimmy-Gia-Bao',13),
('Sara.LAMBELET@cpnv.ch','LAMBELET','Sara',20),
('Camilo-Ernesto.LASSO-GOMEZ@cpnv.ch','LASSO-GOMEZ','Camilo-Ernesto',20),
('Loe.LAVAUD@cpnv.ch','LAVAUD','Loe',4),
('Mahe.LAVAUD@cpnv.ch','LAVAUD','Mahe',5),
('Amos.LE-COQ@cpnv.ch','LE-COQ','Amos',6),
('Thibault.LE-NORMAND@cpnv.ch','LE-NORMAND','Thibault',2),
('Alexis.LEAKOS@cpnv.ch','LEAKOS','Alexis',12),
('Sylvain.LECHAIRE@cpnv.ch','LECHAIRE','Sylvain',6),
('Ivan.LECOMTE@cpnv.ch','LECOMTE','Ivan',12),
('Romain.LENOIR@cpnv.ch','LENOIR','Romain',3),
('Oliwier.LEWANDROWSKI@cpnv.ch','LEWANDROWSKI','Oliwier',2),
('Marina.MACHADO-CAPISTRANO-SILVA@cpnv.ch','MACHADO-CAPISTRANO-SILVA','Marina',8),
('Gabriel.MACHADO-PEREIRA@cpnv.ch','MACHADO-PEREIRA','Gabriel',7),
('Lucas.MACHARD@cpnv.ch','MACHARD','Lucas',10),
('Agathe.MAKUMBI-MBUKA@cpnv.ch','MAKUMBI-MBUKA','Agathe',21),
('Alex.MARGOT@cpnv.ch','MARGOT','Alex',3),
('Antoine.MARTET@cpnv.ch','MARTET','Antoine',10),
('Mei.MARTIN@cpnv.ch','MARTIN','Mei',21),
('Ethan.MARTIN@cpnv.ch','MARTIN','Ethan',1),
('Beatriz.MARTIN-PENALOSA@cpnv.ch','MARTIN-PENALOSA','Beatriz',11),
('Evann.MARTINS@cpnv.ch','MARTINS','Evann',14),
('Jeremy.MARZOLINI@cpnv.ch','MARZOLINI','Jeremy',3),
('Johan-Laurent.MATTHEY@cpnv.ch','MATTHEY','Johan-Laurent',28),
('Valentin.MAURER@cpnv.ch','MAURER','Valentin',10),
('Alessia.MAVRAJ@cpnv.ch','MAVRAJ','Alessia',3),
('Damien.MAYOR@cpnv.ch','MAYOR','Damien',11),
('Colin.MENOUD@cpnv.ch','MENOUD','Colin',3),
('Pierrot.METILLE@cpnv.ch','METILLE','Pierrot',6),
('Loik.MEYLAN@cpnv.ch','MEYLAN','Loik',7),
('Sara-Elodie.MEZENEN@cpnv.ch','MEZENEN','Sara-Elodie',28),
('Garis.MIEHLBRADT@cpnv.ch','MIEHLBRADT','Garis',17),
('Dunia-Alexandra.MIELE@cpnv.ch','MIELE','Dunia-Alexandra',29),
('Ambre.MIELLOT@cpnv.ch','MIELLOT','Ambre',10),
('Khalil-Amadeo.MIRANDA-JACOME@cpnv.ch','MIRANDA-JACOME','Khalil-Amadeo',20),
('Myline.MONDOUX@cpnv.ch','MONDOUX','Myline',28),
('Rui-Miguel.MONTEIRO-PEREIRA@cpnv.ch','MONTEIRO-PEREIRA','Rui-Miguel',5),
('Sebastien.MORAZ@cpnv.ch','MORAZ','Sebastien',8),
('David.MOSER@cpnv.ch','MOSER','David',11),
('Ahmed.MUJANOVIC@cpnv.ch','MUJANOVIC','Ahmed',15),
('Benjamin.MUMINOVIC@cpnv.ch','MUMINOVIC','Benjamin',18),
('Brad-Dylan.MUNOZ@cpnv.ch','MUNOZ','Brad-Dylan',1),
('Mathias.NEGA@cpnv.ch','NEGA','Mathias',21),
('Logan.NGUYEN@cpnv.ch','NGUYEN','Logan',15),
('Bersabeh.NIKODIMOS@cpnv.ch','NIKODIMOS','Bersabeh',29),
('Enzo.NONNENMACHER@cpnv.ch','NONNENMACHER','Enzo',8),
('Theo.NUSSBAUM@cpnv.ch','NUSSBAUM','Theo',2),
('Benjamin.OCONNER@cpnv.ch','OCONNER','Benjamin',5),
('Ayami.OGAY@cpnv.ch','OGAY','Ayami',10),
('Diogo.OLIVEIRA-SOARES@cpnv.ch','OLIVEIRA-SOARES','Diogo',4),
('Naidin.OMEROVIC@cpnv.ch','OMEROVIC','Naidin',1),
('Bibi.ONYEMACHI-MWABANA@cpnv.ch','ONYEMACHI-MWABANA','Bibi',29),
('Fakime-Nur.OZDEMIR@cpnv.ch','OZDEMIR','Fakime-Nur',2),
('Alessandra.PALUMBO@cpnv.ch','PALUMBO','Alessandra',28),
('Jonathan.PENARANDA-GONZALEZ@cpnv.ch','PENARANDA-GONZALEZ','Jonathan',4),
('Julian.PEREZ@cpnv.ch','PEREZ','Julian',4),
('Esteban.PEREZ-NARCISI@cpnv.ch','PEREZ-NARCISI','Esteban',2),
('Judah-Abishek.PERIYASAMY-GHANESHAN@cpnv.ch','PERIYASAMY-GHANESHAN','Judah-Abishek',12),
('Jonatan.PERRET@cpnv.ch','PERRET','Jonatan',19),
('Thomas.PETERMANN@cpnv.ch','PETERMANN','Thomas',5),
('Loic.PEYRAMAURE@cpnv.ch','PEYRAMAURE','Loic',20),
('Fabian.PILLONEL@cpnv.ch','PILLONEL','Fabian',23),
('Pedro.PINTO@cpnv.ch','PINTO','Pedro',7),
('Jorge-Miguel.PINTO-COSTA@cpnv.ch','PINTO-COSTA','Jorge-Miguel',3),
('Miguel.PINTO-GOMES@cpnv.ch','PINTO-GOMES','Miguel',1),
('Diego.PINTO-TOMAZ@cpnv.ch','PINTO-TOMAZ','Diego',3),
('Axel.PITTET@cpnv.ch','PITTET','Axel',18),
('Celia.POLIGNE@cpnv.ch','POLIGNE','Celia',28),
('Thirusan.RAJADURAI@cpnv.ch','RAJADURAI','Thirusan',9),
('Cecile.RAMOS@cpnv.ch','RAMOS','Cecile',21),
('Timothee.RAPIN@cpnv.ch','RAPIN','Timothee',8),
('Sven.RAVAL@cpnv.ch','RAVAL','Sven',4),
('Arnaud.REICHENBACH@cpnv.ch','REICHENBACH','Arnaud',22),
('Nuno.RIBEIRO-PEREIRA@cpnv.ch','RIBEIRO-PEREIRA','Nuno',5),
('Luca.RICHARD@cpnv.ch','RICHARD','Luca',2),
('Matheo.RISSE@cpnv.ch','RISSE','Matheo',1),
('Theo.RIZZO@cpnv.ch','RIZZO','Theo',20),
('Raphael.ROBERT@cpnv.ch','ROBERT','Raphael',4),
('Sam.RODRIGUES-PEREIRA@cpnv.ch','RODRIGUES-PEREIRA','Sam',29),
('Marc-Antoine.ROMAO@cpnv.ch','ROMAO','Marc-Antoine',1),
('Tobias-Luca.ROUCHE@cpnv.ch','ROUCHE','Tobias-Luca',28),
('Antoine.ROULIN@cpnv.ch','ROULIN','Antoine',8),
('Salima.RUFER@cpnv.ch','RUFER','Salima',28),
('Fatime.RUSINOVCI@cpnv.ch','RUSINOVCI','Fatime',29),
('Tiago.SANTOS@cpnv.ch','SANTOS','Tiago',7),
('Nicola-Marco.SCELSI@cpnv.ch','SCELSI','Nicola-Marco',28),
('Ethann.SCHNEIDER@cpnv.ch','SCHNEIDER','Ethann',6),
('Adam.SIFATE@cpnv.ch','SIFATE','Adam',6),
('Ajin.SIVASAMPOO@cpnv.ch','SIVASAMPOO','Ajin',1),
('Zachary.SMITH@cpnv.ch','SMITH','Zachary',1),
('Edward.STEWART@cpnv.ch','STEWART','Edward',5),
('Kristina.STOJADINOVIC@cpnv.ch','STOJADINOVIC','Kristina',21),
('Ivan.STOJILOVIC@cpnv.ch','STOJILOVIC','Ivan',8),
('Philippe.STRASSLE-ZUNIGA@cpnv.ch','STRASSLE-ZUNIGA','Philippe',21),
('Joshua.SURICO@cpnv.ch','SURICO','Joshua',5),
('Leo.TEIXEIRA@cpnv.ch','TEIXEIRA','Leo',2),
('Quentin.TIYANGOU@cpnv.ch','TIYANGOU','Quentin',11),
('Tina.TORRENT@cpnv.ch','TORRENT','Tina',20),
('Yasemin.TUGCU-GUZEL@cpnv.ch','TUGCU-GUZEL','Yasemin',29),
('Hajrudin.TURSUNOVIC@cpnv.ch','TURSUNOVIC','Hajrudin',1),
('Marcos.VALENTE-DA-SILVA@cpnv.ch','VALENTE-DA-SILVA','Marcos',3),
('Margot.VALIN@cpnv.ch','VALIN','Margot',21),
('Youri.VILLIGER@cpnv.ch','VILLIGER','Youri',15),
('Sacha.VOLERY@cpnv.ch','VOLERY','Sacha',4),
('Sven.VOLERY@cpnv.ch','VOLERY','Sven',7),
('Gwenael.WEST@cpnv.ch','WEST','Gwenael',8),
('Valentin.WILHEM@cpnv.ch','WILHEM','Valentin',5),
('Matthieu.WIRZ@cpnv.ch','WIRZ','Matthieu',10),
('Muamer.ZAHIROVIC@cpnv.ch','ZAHIROVIC','Muamer',27),
('Nadia.ZARGUI-MEHRAZ@cpnv.ch','ZARGUI-MEHRAZ','Nadia',28),
('Pablo-Fernando.ZUBIETA-RODRIGUEZ@cpnv.ch','ZUBIETA-RODRIGUEZ','Pablo-Fernando',11)
;

-- -----------------------------------------------------
-- Table `TPI-Manager`.`tpi`
-- -----------------------------------------------------
INSERT INTO `tpi` (`title`, `year`, `Candidates_id`, `Collaborators_id`) VALUES
('Consultation et archivage des sujets donnés lors des PRE-TPI et TPI à l\'aide d\'une application c#', '2023-01-31', 106, 2),
('Mise en service de GPI avec liaison Active Directory', '2023-01-31', 59, 41),
('WIFI multiple SSID', '2023-01-31', 146, 41),
('Mise à jour de la solution de déploiement avec un impact minimisé, de fichiers très volumineux sur les PC d\'une salle', '2023-01-31', 83, 41),
('Déploiement de systèmes d\'exploitation Windows 10 avec le logiciel libre G4L (Ghost for Linux)', '2023-01-31', 128, 41)
;



-- -----------------------------------------------------
-- Table `TPI-Manager`.`technologies`
-- -----------------------------------------------------
INSERT INTO `TPI-Manager`.technologies (name,siteLink)
VALUES
('.net', 'https://dotnet.microsoft.com/en-us/'),
('c#', 'https://dotnet.microsoft.com/en-us/languages/csharp'),
('Microsoft Visual Studio', 'https://visualstudio.microsoft.com/fr/'),
('mariadb', 'https://mariadb.com/'),
('git', 'https://git-scm.com/'),
('draw.io','https://www.draw.io/index.html'),
('Mysql Workbench', 'https://www.mysql.com/products/workbench/'),
('HeidiSql','https://www.heidisql.com/')
;


-- -----------------------------------------------------
-- Table `TPI-Manager`.`tpi_uses_technologies`
-- -----------------------------------------------------
INSERT INTO `TPI-Manager`.tpi_uses_technologies (TPI_id, Technologies_id)
VALUES
(1,1),
(1,2),
(1,3),
(1,4),
(1,5),
(2,5)
;

-- -----------------------------------------------------
-- Table `TPI-Manager`.`experts`
-- -----------------------------------------------------
INSERT INTO `TPI-Manager`.experts (email,lastName,firstName)
VALUES 
('Jean.Paul@gmail.com','Paul','Jean'),
('Jeanne.Pauline@gmail.com','Pauline','Jeanne'),
('Damien.Dupont@gmail.com','Dupont','Damien'),
('Leblanc.Dupond@gmail.com','Dupond','Leblanc')
;


-- -----------------------------------------------------
-- Table `TPI-Manager`.`tpi_has_experts`
-- -----------------------------------------------------
INSERT INTO `TPI-Manager`.tpi_has_experts (TPI_id, Experts_id)
VALUES
(1,3),
(1,4),
(2,1),
(2,2)
;

